# ----------- Windows -----------
- name: Check if Wazuh agent bin exists on Ludus for Windows targets
  ansible.builtin.stat:
    path: "{{ ludus_install_directory }}/resources/windows/wazuh-agent-4.7.3-1.msi"
  register: windows_agent_exists
  delegate_to: localhost

- name: Download the Windows Wazuh agent if it doesn't exist
  ansible.builtin.get_url:
    url: "{{ ludus_wazuh_agent_install_package }}"
    dest: "{{ ludus_install_directory }}/resources/windows/wazuh-agent-4.7.3-1.msi"
    mode: "0644"
  delegate_to: localhost
  when: not windows_agent_exists.stat.exists

- name: Create Ludus directory on Windows target if it doesn't exist
  ansible.windows.win_file:
    path: "{{ ludus_wazuh_install_directory }}"
    state: directory

- name: Copy Elastic agent to Windows target
  ansible.windows.win_copy:
    src: "{{ ludus_install_directory }}/resources/windows/wazuh-agent-4.7.3-1.msi"
    dest: "{{ ludus_wazuh_install_directory }}"

# ----------- Linux (Debian/Ubuntu) -----------
- name: Ensure resources directory exists on Ludus server
  ansible.builtin.file:
    path: "{{ ludus_install_directory }}/resources/linux"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Check if Wazuh agent .deb exists on Ludus server
  ansible.builtin.stat:
    path: "{{ wazuh_agent_local_path }}"
  register: linux_agent_exists
  delegate_to: localhost

- name: Download Wazuh agent .deb to Ludus server
  ansible.builtin.get_url:
    url: "{{ wazuh_agent_deb_url }}"
    dest: "{{ wazuh_agent_local_path }}"
    mode: '0644'
  delegate_to: localhost
  when: not linux_agent_exists.stat.exists